### PR TITLE
Update Rust version

### PR DESCRIPTION
**Pull request by claravanstaden**
To match what Parity is using, also fixes the smoke tests together with https://github.com/Snowfork/snowbridge/pull/1173.

### CODE REVIEW

**Comment by claravanstaden** [comment]
`stable` breaks clippy, so I pinned it to `1.76` instead of stable, which is `1.77`.

**Review by alistair-singh — APPROVED** [review]
+1

**Review by vgeddes — COMMENTED** [review]
Should we also ensure `RUST_NIGHTLY_VERSION` in our `flake.nix` is upgraded to match?

**Review by yrong — APPROVED** [review]
+1

**Pull request merged**
